#!/usr/bin/env bash

BASEDIR=${PWD}

echo "Setting up your Mac..."

# Install Xcode cli tools
xcode-select --install

# Check for Homebrew and install if brew wasn't found
if test ! $(which brew); then
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Update Homebrew recipes
brew update

# Install all our dependencies with bundle (See Brewfile)
brew tap homebrew/bundle
brew bundle

# Install OH-MY-ZSH
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

echo "Setup git credentials"
source ./git-setup

# Symlink dotfiles
ln -sf ${BASEDIR}/.slate ~/
ln -sf ${BASEDIR}/.bash_profile ~/
ln -sf ${BASEDIR}/.zshrc ~/

# Reload bash profile 
source ~/.bash_profile

source ./.macos

source ./dpp-install
